### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ivaniclixx** [caltechads/wagtail-jetstream#1]
Hello,

I've been trying for HOURS now, but can't manage to get anything useful.
I had to install _djunk_ from another github repository. Everything seems configured properly, but how do I define models in order to use the StreamFields, StreamBlocks, ... Any provided example would be great. I tried things like:

from jetstream.fields import FeatureCustomizedStreamField
from jetstream.blocks import FeatureCustomizedStreamBlock

```
    testing = FeatureCustomizedStreamField([
        ('paragraph', FeatureCustomizedStreamBlock()),
    ], blank=True, null=True)

```

But they all fail, either with some error, like:

> Exception Value: | 'str' object has no attribute 'all_blocks'
> -- | --
> venv/lib/python3.6/site-packages/wagtail-2.12a0-py3.6.egg/wagtail/core/blocks/base.py, line 74, in all_blocks

Or by just showing a blank block. What am missing? Tried with the latest Wagtail 2.11.2 and even the latest 2.12a0 from GIT.

Thanks.

**Comment by cnk** [comment]
Sorry you are having trouble getting this working. I can confirm that Jetstream bloks work with Wagtail 2.11rc1 and Django 3.1.2. 

FeatureCustomizedStreamField and FeatureCustomizedStreamBlock are base classes - like their StreamField and StreamBlock equivalents. So without additional configuration, they don't really do anything - especially if you don't have anything that is providing the sites list of features. 

Are you trying to use the blocks Jetstream provides - such as the HeroImageBlock or TwoColumnLayoutBlock? Or is FeatureCustomizedStreamField the feature you are interested in? 

If the former, here is an example page definition. I have had to edit it to take out a lot of stuff that is not included in this repository but I think this should work. 

```
class FlexPage(Page):
    body = FeatureCustomizedStreamField([
        get_block_tuple(TwoColumnBlock()),
        get_block_tuple(ThreeColumnBlock()),
        get_block_tuple(FourColumnBlock()),
        get_block_tuple(SidebarLayoutBlock()),
    ])
```

Unless you have a Features implementation, I would try replacing FeatureCustomizedStreamField with StreamField in the example above.

**Comment by ivaniclixx** [comment]
Okay, so I misunderstood. I thought I could just use a BaseTwoColumnBlock that included all the blocks from jetstream, but I see I have to use them one by one in a StreamField using the get_block_tuple function...
I ended up with:

    body = StreamField(
    COLUMN_PERMITTED_BLOCKS
    , blank=True, null=True)

Because I just wanted to have all the available blocks.

Thank you.

**Comment by cnk** [comment]
The way we use this on our project is there are blocks you can use directly in the page body and there are blocks you can use inside a column of one of the XColumnBlocks - and of course some blocks, like the HeaderBlock, you can use in either context. 

The `get_block_tuple` exists to make some of our nesting and inheritance work. So if you don't care about the XColumnLayout blocks, It may be more straightforward to copy the blocks you are interested in into your own code base and use them as documented in for regular Wagtail blocks.

**Comment by ivaniclixx** [comment]
I see, It's much clearer now. Thank you again for your time.

**Comment by ZackPlauche** [comment]
My wagtail project can't even find jetstream. All you're supposed to do is download the wagtail-jetstream directory into your project folder right?

**Comment by cnk** [comment]
@ZackPlauche The usual way to install wagtail-jetstream into your project project would be to put a line like this in your requirements.txt file: 

-e git+https://github.com/caltechads/wagtail-jetstream.git@1.2.0#egg=wagtail-jetstream

And then make sure you have `jetstream` listed in your INSTALLED_APPS.

But, if you only want a few of the blocks jetstream provides, copying the block and template code into your project might also be a reasonable option.
